version: 2.0
jobs:
  build:
	working_directory: ~/teams
	docker:
		- image: alpine:3.7
		- image: circleci/ruby:2.6.3
	steps:
		- checkout
		- run:
				name: The First Step
				name: Run tests
				command: |
					gem install bundler
					bundle install
					bundle exec rspec
