version: 2.0
jobs:
  build:
    working_directory: ~/
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            bundle exec rspec
